import { FooterIcon, InfoLink, NavLink, Property } from "@/types";

export const NAVLINKS: NavLink[] = [
  {
    id: 1,
    title: "stay",
  },
  {
    id: 2,
    title: "the hotel",
  },
  {
    id: 3,
    title: "eat drink",
  },
  {
    id: 4,
    title: "wellbeing",
  },
  {
    id: 5,
    title: "concierge",
  },
  {
    id: 6,
    title: "about",
  },
  {
    id: 7,
    title: "special deals",
  },
];

export const PROPERTIES: Property[] = [
  {
    id: "56cb91bdc3464f14678934ca",
    propertyTypeId: 224,
    propertyType: false,
    name: "Chalet Murasaki",
    description:
      "This 8 bedroom chalet (487 sqm) features a large master bedroom (55 sqm) with a hinoki en-suite bathroom and a daybed nook for quiet relaxation.",
    code: "CM",
    baseRoom: "",
    gradeId: 22,
    gradeSort: 8,
    locationId: 50,
    accomTypeId: 2,
    viewId: 9,
    kitchenId: 1,
    liftDistanceId: 179,
    villageCentreDistanceId: 181,
    bathrooms: 4,
    standardPax: 17,
    maximumPax: 18,
    soldSeparately: true,
    upgradedFacilities: false,
    amenities: {
      aircon: false,
      appletv: false,
      btspeakers: false,
      cardkey: false,
      chromecast: false,
      fireplace: false,
      hdtv: false,
      jacuzzi: false,
      nespresso: false,
    },
    bedConfigurations: [92, 224, 225, 226, 228],
    status: "healthy",
    floorArea: 487,
    online: true,
    images: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/482255779.jpg?k=2b99ba3f9bf500f6697dac5d926c718d5de4ce63bdf495028ee367487ba49137&o=&hp=1",
    ],
  },
  {
    id: "34cb55756c3464f1467893ca",
    propertyTypeId: 225,
    propertyType: false,
    name: "Chalet Murasaki a",
    description:
      "This 6 bedroom chalet features a large master bedroom (55 sqm) with a hinoki-lined en suite, large walk-in closet and daybed nook for quiet relaxation.",
    code: "CMa",
    baseRoom: "",
    gradeId: 21,
    gradeSort: 6,
    locationId: 50,
    accomTypeId: 2,
    viewId: 9,
    kitchenId: 1,
    liftDistanceId: 179,
    villageCentreDistanceId: 181,
    bathrooms: 3,
    standardPax: 13,
    maximumPax: 14,
    soldSeparately: true,
    upgradedFacilities: false,
    amenities: {
      aircon: false,
      appletv: false,
      btspeakers: false,
      cardkey: false,
      chromecast: false,
      fireplace: false,
      hdtv: false,
      jacuzzi: false,
      nespresso: false,
    },
    bedConfigurations: [92, 230, 231],
    status: "healthy",
    floorArea: 411,
    online: true,
    images: [
      "https://images.halldis.com/photos/402/xwide-asra16:10/1303-010.jpg",
    ],
  },
  {
    id: "34256cb91bdc3464f146789",
    propertyTypeId: 226,
    propertyType: false,
    name: "Chalet Murasaki b",
    description:
      "The 2 bedroom Chalet Murasaki Apartment (75.5 sqm) is fully equipped with all amenities, including 2 large flat-screen cable TVs, high-speed WiFi broadband internet, private ski storage, full kitchen and dining facilities, private laundry room and free parking space.",
    code: "CMb",
    baseRoom: "",
    gradeId: 3,
    gradeSort: 2,
    locationId: 50,
    accomTypeId: 2,
    viewId: 9,
    kitchenId: 1,
    liftDistanceId: 179,
    villageCentreDistanceId: 181,
    bathrooms: 1,
    standardPax: 4,
    maximumPax: 5,
    soldSeparately: true,
    upgradedFacilities: false,
    amenities: {
      aircon: false,
      appletv: false,
      btspeakers: false,
      cardkey: false,
      chromecast: false,
      fireplace: false,
      hdtv: false,
      jacuzzi: false,
      nespresso: false,
    },
    bedConfigurations: [17, 21, 22, 23, 92],
    status: "healthy",
    floorArea: 75,
    online: true,
    images: [
      "https://static.suedtirol.com/supercompanies/13230/images/g15-o.jpg?size=scg",
    ],
  },
  {
    id: "976b913464f14678934ca",
    propertyTypeId: 231,
    propertyType: false,
    name: "Deep Tracks 1",
    description:
      "Located just 200 m from the Hirafu Gondola, this 1 bedroom apartment is ideal for those seeking fresh tracks.",
    code: "DT01",
    baseRoom: "",
    gradeId: 2,
    gradeSort: 1,
    locationId: 16,
    accomTypeId: 1,
    viewId: 11,
    kitchenId: 1,
    liftDistanceId: 179,
    villageCentreDistanceId: 182,
    bathrooms: 1,
    standardPax: 2,
    maximumPax: 3,
    soldSeparately: true,
    upgradedFacilities: true,
    amenities: {
      aircon: false,
      appletv: true,
      btspeakers: true,
      cardkey: true,
      chromecast: false,
      fireplace: false,
      hdtv: false,
      jacuzzi: false,
      nespresso: true,
    },
    bedConfigurations: [8, 9, 92],
    status: "healthy",
    floorArea: 44,
    online: true,
    images: [
      "https://content.jdmagicbox.com/v2/comp/delhi/i4/011pxx11.xx11.181127234922.l3i4/catalogue/oyo-11611-royal-palace-inn-paschim-vihar-delhi-hotels-mesdhtm0fm.jpg",
    ],
  },
  {
    id: "13cb4b73464f678934ca",
    propertyTypeId: 231,
    propertyType: false,
    name: "Deep Tracks 2",
    description:
      "Located just 200 m from the Hirafu Gondola, this 1 bedroom apartment is ideal for those seeking fresh tracks.",
    code: "DT02",
    baseRoom: "",
    gradeId: 2,
    gradeSort: 1,
    locationId: 16,
    accomTypeId: 1,
    viewId: 9,
    kitchenId: 1,
    liftDistanceId: 179,
    villageCentreDistanceId: 182,
    bathrooms: 1,
    standardPax: 2,
    maximumPax: 3,
    soldSeparately: true,
    upgradedFacilities: false,
    amenities: {
      aircon: false,
      appletv: false,
      btspeakers: false,
      cardkey: true,
      chromecast: false,
      fireplace: false,
      hdtv: false,
      jacuzzi: false,
      nespresso: false,
    },
    bedConfigurations: [8, 9, 92],
    status: "healthy",
    floorArea: 44,
    online: true,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoL_66KGYK6O_APYcPColX9tid-zBTwLtKVQ&s",
    ],
  },
];

export const FOOTERICONS: FooterIcon[] = [
  {
    id: 1,
    alt: "facebook",
    icon: "/assets/images/facebook.svg",
  },
  {
    id: 2,
    alt: "instagram",
    icon: "/assets/images/instagram.svg",
  },
  {
    id: 3,
    alt: "advisor",
    icon: "/assets/images/advisor.svg",
  },
  {
    id: 4,
    alt: "x",
    icon: "/assets/images/x.svg",
  },
  {
    id: 5,
    alt: "vimeo",
    icon: "/assets/images/vimeo.svg",
  },
];

export const INFOLINKS: InfoLink[] = [
  {
    id: 1,
    title: "Express Check-in",
  },
  {
    id: 2,
    title: "faq",
  },
  {
    id: 3,
    title: "news",
  },
  {
    id: 4,
    title: "What's On",
  },
  {
    id: 5,
    title: "careers",
  },
  {
    id: 6,
    title: "owners",
  },
  {
    id: 7,
    title: "invest",
  },
  {
    id: 8,
    title: "contact",
  },
];
